name: Pipeline 3

on:
  workflow_run:
    workflows: ["Pipeline 2"]
    types:
      - completed

jobs:
  check_result:
    runs-on: ubuntu-latest
    steps:
      - name: Check result of Pipeline 2
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Pipeline 2 failed."
            exit 1
          fi

      - name: Trigger Pipeline 1 if successful
        run: |
          echo "Triggering Pipeline 1..."
          gh workflow run 'Pipeline 1'
