name: Pipeline 2

on:
  workflow_run:
    workflows: ["Pipeline 1"]
    types:
      - completed

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        run: echo "Pipeline 1 completed successfully! Running tasks in Pipeline 2."
