name: Pipeline_1

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notify about it
        uses: ./.github/workflows/slack.yml
        with:
          job_status: ${{ job.status }}
          slack_url: "slack.com"
          job_id: ${{ github.run_id }}
