name: Pipeline 3

on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["Pipeline 2"]
#    types:
#      - completed

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  check_result:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Random msg
        run: |
          echo "Random msg!!!"

  exec_new:
    needs: check_result
    uses: ./.github/workflows/pipeline_1.yml

