name: Pipeline_2

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, reopened ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_run:
    workflows: [ Pipeline_1 ]
    types: [ completed ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        run: | 
          echo "Running tasks in Pipeline 2."
#          exit 1
