name: Pipeline_1

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Choose the build type (build1 or build2)'
        required: true
        default: 'build1'
  workflow_call:

jobs:
  build1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_type == 'build1' }}
    outputs:
      job_status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."

      - name: Job Result
        id: set_status
        run: |
          echo "status=$?" >> $GITHUB_OUTPUT
          

  build2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_type == 'build2' }}
    outputs:
      job_status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."

      - name: Job Result
        id: set_status
        run: |
          echo "status=$?" >> $GITHUB_OUTPUT

  notify:
    needs: [build1, build2]
    uses: ./.github/workflows/slack.yml
    with:
      job_status: ${{ needs.build1.outputs.status || needs.build2.outputs.status }}
      slack_url: "slack.com"
      job_id: ${{ github.run_id }}
