name: Pipeline_1

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Choose the build type (build1 or build2)'
        required: true
        default: 'build1'
  workflow_call:

jobs:
  build1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_type == 'build1' }}
    outputs:
      status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run some tasks
        run: |
          pytest tests/ --junit-xml=report.xml
      - name: Analyze report
        id: pytest-results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: report.xml
          summary: true
          fail-on-empty: true
          title: Test results
      - name: Job Result
        id: set_status
        run: |
          echo "status=${{ steps.pytest-results.outcome }}" >> $GITHUB_OUTPUT
          

  build2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_type == 'build2' }}
    outputs:
      status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."

      - name: Job Result
        id: set_status
        run: |
          echo "status=$?" >> $GITHUB_OUTPUT

  notify:
    needs: [build1, build2]
    if: always()
    uses: ./.github/workflows/slack.yml
    with:
      job_status: ${{ needs.build1.outputs.status || needs.build2.outputs.status }}
      slack_url: "slack.com"
      job_id: ${{ github.run_id }}
