name: Pipeline_1

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{
            github.event_name == 'workflow_dispatch' && github.event.inputs.tagbranch
            || github.event_name == 'workflow_run' && github.event.workflow_run.head_branch
            }}

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."