name: Pipeline_1

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Choose the build type (build1 or build2)'
        required: true
        default: 'build1'
  workflow_call:

jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ ${{ steps.set_status.outputs.status }} }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."

  build2:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ ${{ steps.set_status.outputs.status }} }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some tasks
        run: echo "Running tasks in Pipeline 1."

  notify:
    needs: [build1, build2]

    uses: ./.github/workflows/slack.yml
    with:
      job_status: ${{ needs.build1.outputs.job_status || needs.build2.outputs.job_status }}
      slack_url: "slack.com"
      job_id: ${{ github.run_id }}
