name: Pipeline 3

on:
  workflow_dispatch:

jobs:
  check_result:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Random msg
        run: |
          echo "### Locust Test Results" >> $GITHUB_STEP_SUMMARY
          echo "| Request Type | Requests | Failures | Median Response Time |" >> $GITHUB_STEP_SUMMARY
          echo "|-------------|----------|----------|----------------------|" >> $GITHUB_STEP_SUMMARY
          awk -F, 'NR>1 {print "| " $2 " | " $3 " | " $4 " | " $7 " |"}' small_stats.csv >> $GITHUB_STEP_SUMMARY
