name: Pipeline_1

on:
  workflow_dispatch:
    inputs:
      tagbranch:
        description: 'tag/branch to build from. Note that due current limitation the tag/branch MUST be the same for BE & FE repos'
        required: true
      services:
        description: 'services to build'
        required: false
        default: 'cd fe be pg pg16 pl-gpu pl-cpu healthcheck installer'
      licenseperiod:
        description: 'obfuscation period with default as per packager default'
        required: false
        default: 90
      releaseversion:
        description: 'release version such as 2.15.5'
        required: true
      devBuild:
        type: boolean
        description: 'dev build (dev build is pushed to dev repos)'
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo deploy
        run: |
          echo "Pipeline 1"

  run-tests:
    needs: deploy
    uses: ./.github/workflows/pipeline_2.yml
    # if: ${{ github.event.inputs.services == 'cd fe be pg pg16 pl-gpu pl-cpu healthcheck installer' && !github.event.inputs.devBuild }}
    if: ${{ !github.event.inputs.devBuild }}
    with:
      tagbranch: ${{ github.event.inputs.tagbranch }}
      releaseversion: ${{ github.event.inputs.releaseversion }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
