name: Publist Report As GH Page

on:
  workflow_dispatch:

jobs:
  permissions:
    id-token: write
    pages: write  
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          mkdir report
          python -m pip install -U pip
          python -m pip install -r req.txt
      - name: Test it
        continue-on-error: true
        run: |
          pytest tests/ --junitxml=report/report.xml
      - uses: actions/upload-artifact@master
        with:
          name: test_report
          path: report
          if-no-files-found: error

  test_and_deploy_page:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: test_report
          path: .
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main
#      - name: Setup Pages
#        uses: actions/configure-pages@v2
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v1
#        with:
#          # Upload the coverage directory from the repository
#          path: './report'
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1
