name: Publist Report As GH Page

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  make-push-into-protected-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Create GitHub App Token
#        id: app-token
#        uses: actions/create-github-app-token@v1
#        with:
#          app-id: ${{ secrets.APP_ID }}
#          private-key: ${{ secrets.APP_KEY }}
#
#      - name: Get GitHub App User ID
#        id: get-user-id
#        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
#        env:
#          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
#
#      - name: Git config
#        env:
#          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
#        run: |
#          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
#          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
      - name: Git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          echo "\nTest" >> README.md
          git add .
          git commit -m "Update Readme file"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main --force
#          git push https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git HEAD:main --force
#          git push origin main --force